# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  # build-firebase:
  #   docker:
  #     - image: eeeeeric/circleci-docker-image:latest
  #   working_directory: ~/mystic-the-get-together
  #   steps:
  #     - checkout
  #     # Download and cache dependencies
  #     - restore_cache:
  #         keys:
  #           - v1-dependencies-{{ checksum "firebase/functions/package.json" }}
  #           # fallback to using the latest cache if no exact match is found
  #           - v1-dependencies-
  #     - run: 
  #       name: Install Node Dependencies for Cloud Functions
  #       command: |
  #         cd firebase/functions
  #         npm install
  #     - save_cache:
  #         paths:
  #           - firebase/functions/node_modules
  #         key: v1-dependencies-{{ checksum "firebase/functions/package.json" }}

  deploy-firebase-test:
    docker:
      - image: eeeeeric/circleci-docker-image:latest
    working_directory: ~/mystic-the-get-together
    steps:
      - checkout
      - restore_cache:
          keys:
            - functions-dependencies-{{ checksum "firebase/functions/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - functions-dependencies-
      - run: 
        name: Install Node Dependencies for Cloud Functions
        command: |
          cd firebase/functions
          npm install
      - save_cache:
          paths:
            - firebase/functions/node_modules
          key: functions-dependencies-{{ checksum "firebase/functions/package.json" }}
      - run:
        name: Deploy Cloud Functions to Firebase TEST Environment
        command: |
        cd firebase
        firebase use test
        firebase deploy --token=$FIREBASE_TOKEN
  
  test-firebase-cloud-functions:
    docker:
      - image: eeeeeric/circleci-docker-image:latest
    working_directory: ~/mystic-the-get-together
    steps:
      - checkout
      - restore_cache:
          keys:
            - functions-dependencies-{{ checksum "firebase/functions/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - functions-dependencies-
      - run: 
        name: Install Node Dependencies for Cloud Functions
        command: |
          cd firebase/functions
          npm install
      - save_cache:
          paths:
            - firebase/functions/node_modules
          key: functions-dependencies-{{ checksum "firebase/functions/package.json" }}
      - run:
        name: Execute Firebase Cloud Functions Tests
        command: |
        cd firebase/functions
        echo $SERVICE_ACCOUNT_CREDENTIALS_JSON > service-account-credentials.json
        npm run fb-clean && npm test

  test-firebase-security-rules:
    docker:
      - image: eeeeeric/circleci-docker-image:latest
    working_directory: ~/mystic-the-get-together
    steps:
      - checkout
      - restore_cache:
          keys:
            - security-rules-dependencies-{{ checksum "firebase/tests/firestore-rules/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - security-rules-dependencies-
      - run: 
        name: Install Node Dependencies for Cloud Functions
        command: |
          cd firebase/tests/firestore-rules
          npm install
      - save_cache:
          paths:
            - firebase/tests/firestore-rules/node_modules
          key: security-rules-dependencies-{{ checksum "firebase/tests/firestore-rules/package.json" }}
      - run:
        name: Execute Firestore Security Rules Tests
        command: |
        cd firebase/tests/firestore-rules
        echo $SERVICE_ACCOUNT_CREDENTIALS_JSON > service-account-credentials.json
        npm test


workflows:
  version: 2
  test:
    jobs:
      - deploy-firebase-test
      - test-firebase-cloud-functions:
          requires:
            - deply-firebase-test
      - test-firebase-security-rules:
          requires:
            - test-firebase-cloud-functions
