# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  firebase-deploy: cloudliner/firebase-deploy@0.0.2
general:
  branches:
    only:
      - circleci
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.15.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/mystic-the-get-together

    steps:
      - checkout
      - run: cd firebase
      - run: echo $TEST_VAR
      # - firebase-deploy:
      #   token: $FIREBASE_DEPLOY_TOKEN
    #   # Download and cache dependencies
    #   - restore_cache:
    #       keys:
    #         - v1-dependencies-{{ checksum "package.json" }}
    #         # fallback to using the latest cache if no exact match is found
    #         - v1-dependencies-

    #   - run: yarn install

    #   - save_cache:
    #       paths:
    #         - node_modules
    #       key: v1-dependencies-{{ checksum "package.json" }}

    #   # run tests!
    #   - run: yarn test
    # test:


# workflows:
#   version: 2
#   build-test-and-deploy:
#     jobs:
#       - build
#       - test1:
#           requires:
#             - build
#       - test2:
#           requires:
#             - test1
#       - deploy:
#           requires:
#             - test2
